apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: hello-world
spec:
  ports:
  - name: 3333-tcp
    port: 3333
  selector:
    deployment: hello-world
